# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ngame.proto",\n\x0cPositionData\x12\r\n\x05pos_x\x18\x01 \x01(\x02\x12\r\n\x05pos_y\x18\x02 \x01(\x02"A\n\x07NpcData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02"P\n\x15PositionUpdateMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12$\n\rposition_data\x18\x02 \x01(\x0b\x32\r.PositionData"P\n\x18NpcPositionUpdateMessage\x12\x0e\n\x06npc_id\x18\x01 \x01(\t\x12$\n\rposition_data\x18\x02 \x01(\x0b\x32\r.PositionData"@\n\x19NewPlayerConnectedMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t"&\n\x11PlayerAuthMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t"-\n\x18PlayerDisconectedMessage\x12\x11\n\tplayer_id\x18\x01 \x01(\t"\x18\n\x07TileRow\x12\r\n\x05tiles\x18\x01 \x03(\x08"@\n\x07MapData\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x16\n\x04rows\x18\x03 \x03(\x0b\x32\x08.TileRow"\xc3\x02\n\rSocketMessage\x12\x31\n\x0fposition_update\x18\x01 \x01(\x0b\x32\x16.PositionUpdateMessageH\x00\x12:\n\x14new_player_connected\x18\x02 \x01(\x0b\x32\x1a.NewPlayerConnectedMessageH\x00\x12\x38\n\x13player_disconnected\x18\x03 \x01(\x0b\x32\x19.PlayerDisconectedMessageH\x00\x12\x38\n\x13npc_position_update\x18\x04 \x01(\x0b\x32\x19.NpcPositionUpdateMessageH\x00\x12\x1c\n\x08map_data\x18\x05 \x01(\x0b\x32\x08.MapDataH\x00\x12)\n\x0bplayer_auth\x18\x06 \x01(\x0b\x32\x12.PlayerAuthMessageH\x00\x42\x06\n\x04\x64\x61tab\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "game_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _POSITIONDATA._serialized_start = 14
    _POSITIONDATA._serialized_end = 58
    _NPCDATA._serialized_start = 60
    _NPCDATA._serialized_end = 125
    _POSITIONUPDATEMESSAGE._serialized_start = 127
    _POSITIONUPDATEMESSAGE._serialized_end = 207
    _NPCPOSITIONUPDATEMESSAGE._serialized_start = 209
    _NPCPOSITIONUPDATEMESSAGE._serialized_end = 289
    _NEWPLAYERCONNECTEDMESSAGE._serialized_start = 291
    _NEWPLAYERCONNECTEDMESSAGE._serialized_end = 355
    _PLAYERAUTHMESSAGE._serialized_start = 357
    _PLAYERAUTHMESSAGE._serialized_end = 395
    _PLAYERDISCONECTEDMESSAGE._serialized_start = 397
    _PLAYERDISCONECTEDMESSAGE._serialized_end = 442
    _TILEROW._serialized_start = 444
    _TILEROW._serialized_end = 468
    _MAPDATA._serialized_start = 470
    _MAPDATA._serialized_end = 534
    _SOCKETMESSAGE._serialized_start = 537
    _SOCKETMESSAGE._serialized_end = 860
# @@protoc_insertion_point(module_scope)
